name: Plagiarism detector

on:
  workflow_run:
    workflows: ['Test Report']                     # runs after CI workflow
    types:
      - completed

jobs:

  PlagiarismChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Plagiarism checker
        uses: Giviruk/plagiarism-action@main
        with:
          github-access-token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: ${{ github.repository }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plagiarism-checker-report
          path: ${{ github.workspace }}/outputs
